services:
  ddap:
    image: "zouloux/docker-debian-apache-php:v2-php8.3"
    volumes:
      - './app:/var/www/app'
      - './lib:/var/www/lib'
      - './public:/var/www/public'
      - './vendor:/var/www/vendor'
      - './data:/var/www/data'
      - './composer.json:/var/www/composer.json'
      - './.env:/var/www/.env'
    ports:
      - 8080:80
    environment:
      DDAP_DEVTOOLS: 'true'
      DDAP_PUBLIC_PATH: '/var/www/public'